---
production:
  name_technical_secretary: Hola
  e_mail_technical_secretary: nanish_20@hotmail.com
  truncate_length: '20'
  notification_time: '10'
  developper_id: '113619161063904399388'
  developper_key: AIzaSyCGpMd7fnGN4FwAChD4I97O3auFvk4nbwQ
  key_path_p12: "/home/mbyte/Documents/contratos/contracts/INBappweb-a33f05a2b051.p12"
  developper_email: inb-321@inb-appweb.iam.gserviceaccount.com
  calendar_id: contratos.inb.unam@gmail.com
  e_mail_create_contract: Aviso de creacion de contrato de mantenimiento.
  e_mail_update_contract: Aviso de actualizacion de informacion del contrato.
  e_mail_create_renewal: Aviso de renovacion de contrato de mantenimiento.
  e_mail_update_renewal: Aviso de actualizacion de renovacion.
  e_mail_create_siteview: Aviso de una visita programada.
  e_mail_update_siteview: Aviso de actualizacion de una visita programada.
