---
production:
  name_technical_secretary: Hola
  e_mail_technical_secretary: nanish_20@hotmail.com
  truncate_length: '20'
  notification_time: '10'
  developper_id: 109856604582-208qmf2tc8gbqpki4hkajgsl2mgh3va5.apps.googleusercontent.com
  developper_key: AIzaSyCRH1hazwsIa5wm9-CRicRxvkVxId3Nx1s
  key_path_p12: "/home/mbyte/Documents/contratos/contracts/unam-b563e3112a76.p12"
  developper_email: 109856604582-208qmf2tc8gbqpki4hkajgsl2mgh3va5@developer.gserviceaccount.com
  calendar_id: java4ever.sys@gmail.com
  e_mail_create_contract: Aviso de creacion de contrato de mantenimiento.
  e_mail_update_contract: Aviso de actualizacion de informacion del contrato.
  e_mail_create_renewal: Aviso de renovacion de contrato de mantenimiento.
  e_mail_update_renewal: Aviso de actualizacion de renovacion.
  e_mail_create_siteview: Aviso de una visita programada.
  e_mail_update_siteview: Aviso de actualizacion de una visita programada.
