---
production:
  name_technical_secretary: Prueba de nombre
  e_mail_technical_secretary: java4ever.sys@gmail.com
  truncate_length: '20'
  notification_time: '10'
  developper_id: 109856604582-208qmf2tc8gbqpki4hkajgsl2mgh3va5.apps.googleusercontent.com
  developper_key: AIzaSyCRH1hazwsIa5wm9-CRicRxvkVxId3Nx1s
  key_path_p12: C:\Sites\contracts\unam-b563e3112a76.p12
  developper_email: 109856604582-208qmf2tc8gbqpki4hkajgsl2mgh3va5@developer.gserviceaccount.com
  calendar_id: java4ever.sys@gmail.com
  e_mail_create_contract: Aqui puede escribir el texto predeterminado para el correo.
  e_mail_update_contract: Aqui puede escribir el texto predeterminado para el correo.
  e_mail_create_renewal: Aqui puede escribir el texto predeterminado para el correo.
  e_mail_update_renewal: Aqui puede escribir el texto predeterminado para el correo.
  e_mail_create_siteview: Aqui puede escribir el texto predeterminado para el correo.
  e_mail_update_siteview: Aqui puede escribir el texto predeterminado para el correo.
